import Head from "next/head";
import Image from "next/image";
import SongCard from "../components/SongCard";
import styles from "@/styles/Home.module.scss";
import { homePageSongsList } from "../helpers/mock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <h1>Recently played</h1>
        <section className={styles["home__recently-played"]}>
          {homePageSongsList.map((item) => {
            return (
              <SongCard
                key={item.id}
                imageSrc={item.imageSource}
                songName={item.name}
                artistName={item.artist}
                songSource={item.source}
              />
            );
          })}
        </section>
      </main>
    </>
  );
}
