import Head from "next/head";
import SongCard from "../components/SongCard";
import styles from "@/styles/Home.module.scss";
import { homePageSongsList } from "../helpers/mock";
import { useSelector } from "react-redux";

export default function Home() {
  const likedSongsList = useSelector((state: any) => state.likedSongs);
  console.log(likedSongsList);

  return (
    <>
      <Head>
        <title>Spotify Clone | Liked Songs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <h1>Liked Songs</h1>
        <section className={styles["home__recently-played"]}>
          {likedSongsList.map((item: any) => {
            const { id, songThumbnail, name, artistName, songLink } =
              item.currentSong;

            return (
              <SongCard
                key={id}
                imageSrc={songThumbnail}
                songName={name}
                artistName={artistName}
                songSource={songLink}
                songId={id}
              />
            );
          })}
        </section>
      </main>
    </>
  );
}
